"""Crear tabla alumnos

Revision ID: 2abe3572bb66
Revises: 9af475f41058
Create Date: 2026-02-21 09:38:46.933941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abe3572bb66'
down_revision = '9af475f41058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido_materno', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('apellido_materno')

    # ### end Alembic commands ###
