"""Crear tabla alumnos

Revision ID: 7707a2b9238a
Revises: 71d487d2a7c3
Create Date: 2026-02-21 09:19:37.619571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7707a2b9238a'
down_revision = '71d487d2a7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
