"""Actualizacion base de datos v2

Revision ID: a3ebe4955f07
Revises: 3ac792cc8f64
Create Date: 2026-03-02 14:18:22.195056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3ebe4955f07'
down_revision = '3ac792cc8f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.drop_column('descipcion')

    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialidad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('cursos')
        batch_op.drop_column('especialiad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialiad', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('cursos', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('created_date')
        batch_op.drop_column('especialidad')

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descipcion', mysql.TEXT(), nullable=True))
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
